version: '3.7'
services:
  pgsql:
    image: postgres:14.4
    container_name: eq-psql
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: eqadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eqraidbot
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - 'pg_data:/var/lib/postgresql/data/pgdata'

volumes:
  pg_data: